services:
  php:
    image: symfony-php-fpm
    restart: always
    container_name: php-fpm
    logging:
      driver: json-file
      options:
        max-size: "20m"
    env_file:
      - ./symfony-app/.env
    # volumes:
    #   - .:/var/www/app

  nginx:
    image: nginx:alpine3.21
    restart: always
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "20m"
    volumes:
      - ./symfony-app:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php