services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: php-fpm
    logging:
      driver: json-file
      options:
        max-size: "20m"
    env_file:
      - .env
    volumes:
      - .:/var/www/app

  nginx:
    image: nginx:alpine3.21
    restart: always
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "20m"
    volumes:
      - .:/var/www/app
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - php