replicaCount: 1

image:
  phpFpm:
    repository: symfony-php-fpm
    tag: latest
    pullPolicy: Always
  nginx:
    repository: nginx
    tag: alpine3.21
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

nginx:
  config: |
    server {
        listen 80;
        server_name _;
        root /var/www/public;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT /var/www/public;
        }

        location ~ /\.ht {
            deny all;
        }
    }
