replicaCount: 1

image:
  phpFpm:
    repository: salvasser/symfony-php-fpm
    tag: latest
    pullPolicy: Always
  nginx:
    repository: nginx
    tag: alpine3.21
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

nginx:
  config: |
    server {
        listen 80;
        server_name _;
        root /var/www/app/public;
        index index.php;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

    }
